### ISSUE TITLE
Remove API key

### ISSUE THREAD

**Issue by KawaiiGator** [gendered/gender-specific#1]
You've added a secret API key to your repo. I'm not familiar with the service but you should revoke that key if you haven't already. Once you've done that you should remove the old key and decide how you're going to handle a new key. Popular options include:

* Leaving the key string empty and filling it in when you make a working copy of the script
* Getting the key from a file that you don't track with git
* Getting the key from an environmental variable that you set at runtime

I don't recommend the first one.

**Comment by oa495** [comment]
@KawaiiGator yes meant to do this, it's expired anyway but will go ahead thanks!
